src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use DateTime;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length="255")
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *      mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=1000) 
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean")
     */
    private $sold = false;

    /**
     * @ORM\ManyToMany(targetEntity=Option::class, inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity=Agence::class, inversedBy="properties")
     */
    private $agences;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
        $this->agences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;
        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;
        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;
        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;
        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;
        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;
        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;
        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;
        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;
        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = new \DateTime();
        //$this->created_at = $created_at;
        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }
        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->removeElement($option)) {
            $option->removeProperty($this);
        }
        return $this;
    }

    /**
     * @return null|string
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filname
     * @return Property
     */
    public function setFilename(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;   
    }

    /**
     * @return null|File
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param null|File $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if (null !== $imageFile) {
            $this->updated_at = new \DateTime();
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /**
     * @return Collection|Agence[]
     */
    public function getAgences(): Collection
    {
        return $this->agences;
    }

    public function addAgence(Agence $agence): self
    {
        if (!$this->agences->contains($agence)) {
            $this->agences[] = $agence;
            $agence->addProperty($this);
        }

        return $this;
    }

    public function removeAgence(Agence $agence): self
    {
        if ($this->agences->removeElement($agence)) {
            $agence->removeProperty($this);
        }

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Agence;
use App\Entity\Option;
use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\QueryBuilder as ORMQueryBuilder;
use PhpParser\Parser\Multiple;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', null, ['label' => 'Nom de la propriete'])
            ->add('description', null, ['label' => 'Description'])
            ->add('surface', null, ['label' => 'Surface'])
            ->add('rooms', null, ['label' => 'Pieces'])
            ->add('bedrooms', null, ['label' => 'Chambre'])
            ->add('floor', null, ['label' => 'Etages'])
            ->add('price', null, ['label' => 'Prix'])
            ->add('heat', ChoiceType::class, ['choices' => $this->getChoices()], [
                'label' => 'Chauffage'
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => 'multiple',
                'required' => false,
                'label' => false,
            ])
            ->add('agences', EntityType::class, [
                'required' => false,
                'label' => false,
                'class' => Agence::class,
                'choice_label' => 'name',
                'multiple' => 'multiple', 
            ])

            ->add('imageFile', FileType::class, [
                'required' => false,
            ])

            ->add('city', null, ['label' => 'Ville'])
            ->add('address', null, ['label' => 'Adresse'])
            ->add('postal_code', null, ['label' => 'Code Postal'])
            ->add('sold', null, ['label' => 'Vendu']);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }

    /**********  pris sur internet  ************/
    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach ($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}           
?>

src/Controller/PropertyController.php
<?php

namespace App\Controller;
use App\Controller\CAgence;
use App\Entity\CAgence as EntityCAgance;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\CAgenceType;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @var ObjectManadger
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em; 
    }

    /**
     * @Route("/biens", name="property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page',1),
            12
        );
        return $this->render('property/index.html.twig', [
            'current_menu'  => 'properties',
            'properties'    => $properties,
            'form'          => $form->createView() 
        ]);

    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements ={"slug": "[a-z0-9\-]*"})
     * @return Property $property
     * @return Response
     */
    public function show(Property $property, string $slug, Request $request):Response
    {
        if($property->getSlug() !== $slug)
        {
            $this->redirectToRoute('property.show', [
                'id' => $property->getId(), 
                'slug' => $property->getSlug()
            ], 301); 
        }
        
        $cagence = new EntityCAgance();
        $cagence->setProperty($property);
        $form = $this->createForm(CAgenceType::class, $cagence);
        
        if ($form->isSubmitted() && $form->isValid())
        {
            $this->addFlash('success', 'Votre mail à bien été envoyé');
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(), 
                'slug' => $property->getSlug()
            ], 301); 
        }

        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties',
            'form' => $form->createView()]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    
    <div class="card-body">
    {% if property.filename %}
    <img src="{{ vich_uploader_asset(property, 'imageFile') }}" alt="card-img-top" style="width: 100%; height:230px;">
    {% else %}
    <img src="{{ '/images/properties/nophoto.jpg' }}" alt="card-img-top" style="width: 300px; height:230px;">
    {% endif %}
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text">{{ property.surface }}m² - {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size:2rem; font-weight: bold;">
            {{ property.formatedPrice }} €
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Acheter ou vendre un bien' %}

{% block body %}
    <div class="container mt-4">
        <div class="jumbotron"> 
            <div class="container">
                <button id="togg2" class="btn btn-primary">Afficher / Cacher les options de recherche</button>
                <br><br>
                {{ form_start(form) }}
                    <div class="form_row">
                        <div id="d2">    
                            <div class="row">
                                <div class="col-md-5">{{ form_row(form.minSurface) }}</div>
                                <div class="col-md-5">{{ form_row(form.maxPrice) }}</div>
                            </div>
                            <div class="row">
                                <p>Options :</p>
                                <div>{{ form_row(form.options)}}</div>
                                <p>Agences :</p>
                                <div>{{ form_row(form.agences)}}</div>
                            </div>
                            
                            <div class="col">
                                <button class="btn btn-primary">Rechercher</button>
                            </div>
                        </div>
                    </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>

    <br>
    <div class="container mt-4">
        <h1>Voir tous les biens</h1>

        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {% include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }} 
        </div> 
    </div>

    <style>
    .pagination {
        justify-content: center;
    }

    </style>

    <script>
        d2.style.display = "none";
        function togg(){
            if(getComputedStyle(d2).display != "none"){
                d2.style.display = "none";
            } else {
                d2.style.display = "block";
            }
        };
        togg2.onclick = togg;
    </script>
  
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-7">
                {% if property.filename %}
                    <img src="{{ vich_uploader_asset(property, 'imageFile') }}" alt="card-img-top" style="width: 700px; height:430px;">
                {% else %}
                    <img src="{{ '/images/properties/nophoto.jpg' }}" alt="card-img-top" style="width: 650px; height:475px;">
                {% endif %}
            </div>
            <div class="col-md-4">
            </br></br></br></br></br>
                <h1>{{ property.title }}</h1>
                <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
                <div class="text-primary" style="font-size: 2rem; font-weight: bold;">{{ property.formatedPrice }} €</div>
            </div>
        </div>
        </br></br>
        <nav class="nav nav-tabs" id="tabs"></nav> 

        <p>
        {{ property.description | nl2br }}
        </P>

        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface Habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }}</td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{ property.floor }}</td>
                    </tr>
                    <tr>
                        <td>Chaffage</td>
                        <td>{{ property.heatType }}</td>
                    </tr>
                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificité(s)</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                    <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
            </div>
        </div>

        <div id="contactForm" class="mt-4">
            <h3>Contacter une Agence</h3>
            {{form_start(form)}}
                <div class="row">
                    <p>Selectionné une ou plusieurs agences :</p>
                    <div class="col">{{ form_row(form.agences) }}</div>
                </div>
                <div class="row">
                    <div class="col">{{ form_row(form.firstname) }}</div>
                    <div class="col">{{ form_row(form.lastname) }}</div>
                </div>
                <div class="row">
                    <div class="col">{{ form_row(form.phone) }}</div>
                    <div class="col">{{ form_row(form.email) }}</div>
                </div>
                
            {{ form_rest(form) }}

                <input type="submit" value="Submit" class="btn btn-primary">

            {{ form_end(form) }}   
        </div>
{% endblock %}